services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archon_be
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=archon
      - PORT=3000
      - COOKIE_SECURE=true
      - COOKIE_SAMESITE=none
      - COOKIE_PATH=/
      - NODE_ENV=development
      - JWT_ISS=http://localhost:3333
      - JWT_AUD=your-audience
      - JWT_EXPIRATION=900
      - JWT_REFRESH_EXPIRATION=1209600
      - JWT_KID=your-key-id
      - JWT_KEY_PRIVATE_PATH=./secrets/token-keys/private.key
      - JWT_KEY_PUBLIC_PATH=./secrets/token-keys/public.key

    volumes:
      - .:/app
    command: npm run start:dev
  postgres:
    image: postgres:16-alpine
    container_name: archonDb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: archon
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: