import {
  GameSetupInterface,
  LightUnitsEnum,
  ColorEnum,
  DarkUnitsEnum,
} from '../interface/gameSetupInterface';

export const BaseBoardLayout: GameSetupInterface = [
  [
    {
      unit: LightUnitsEnum.valkyrie,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: LightUnitsEnum.archer,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: true,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.manticore,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.banshee,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
  ],
  [
    {
      unit: LightUnitsEnum.golem,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: LightUnitsEnum.knight,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: DarkUnitsEnum.goblin,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.troll,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
  ],
  [
    {
      unit: LightUnitsEnum.unicorn,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: LightUnitsEnum.knight,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.goblin,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: DarkUnitsEnum.basilisk,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
  ],
  [
    {
      unit: LightUnitsEnum.djinni,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: LightUnitsEnum.knight,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.goblin,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.shapeshifter,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
  ],
  [
    {
      unit: LightUnitsEnum.wizard,
      color: ColorEnum.light,
      isPointOfPower: true,
      cycling: false,
    },
    {
      unit: LightUnitsEnum.knight,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: true,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: DarkUnitsEnum.goblin,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: DarkUnitsEnum.sorceress,
      color: ColorEnum.dark,
      isPointOfPower: true,
      cycling: false,
    },
  ],
  [
    {
      unit: LightUnitsEnum.phoenix,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: LightUnitsEnum.knight,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.goblin,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.dragon,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
  ],
  [
    {
      unit: LightUnitsEnum.unicorn,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: LightUnitsEnum.knight,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.goblin,
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: DarkUnitsEnum.basilisk,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
  ],
  [
    {
      unit: LightUnitsEnum.golem,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: LightUnitsEnum.knight,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: DarkUnitsEnum.goblin,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.troll,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
  ],
  [
    {
      unit: LightUnitsEnum.valkyrie,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: LightUnitsEnum.archer,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: true,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light1,
      isPointOfPower: false,
      cycling: true,
    },
    {
      unit: 'EMPTY',
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.manticore,
      color: ColorEnum.dark,
      isPointOfPower: false,
      cycling: false,
    },
    {
      unit: DarkUnitsEnum.banshee,
      color: ColorEnum.light,
      isPointOfPower: false,
      cycling: false,
    },
  ],
];
